<?php
function my_block_info() {
  $blocks['like_share_face'] = array(
    'info' => t('Like and share Facebook'),
  );

  return $blocks;
}
function my_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'like_share_face':
      $block['content'] = my_return_like_face();
      break;

}
  return $block;
}

function my_return_like_face() {
 $nid = arg(1);
 $path_term = drupal_get_path_alias('node/'.$nid);
 $ouput = '    <div id="fb-root"></div>';
 $js = '
    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5&appId=1439865049640999";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, "script", "facebook-jssdk"));
 ';
  drupal_add_js($js, array('scope' => 'footer', 'type' => 'inline'));
  $ouput .= "
 <div class='fb-like' data-href=".$path_term.'
  data-layout="button" data-action="like" data-show-faces="false" data-share="true"></div>
 ';
    return $ouput;
}
